default: &default
  adapter: mysql2
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: techpit-match_development

test:
  <<: *default
  database: techpit-match_test

production:
  <<: *default
  databsase: techpit-match_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock
